# .github/workflows/daily_report.yml

name: Run Double Bottom Report

on:
  # Schedule to run at 16:30 UTC, which is 10:00 PM IST
  schedule:
    - cron: '30 16 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-email-report:
    runs-on: ubuntu-latest

    steps:
      # 1. Checks out your repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Installs the necessary Python libraries
      - name: Install dependencies
        run: |
          pip install git+https://github.com/angel-one/smartapi-python.git
          pip install pandas logzero websocket-client pyotp
          pip install pandas logzero websocket-client pyotp scipy
          pip install pandas logzero websocket-client pyotp scipy matplotlib
          pip install pandas logzero websocket-client
          pip install -r requirements.txt

      # 4. Runs your Python script to generate the PDF
      - name: Run stock analysis script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          USER_ID: ${{ secrets.USER_ID }}
          PIN: ${{ secrets.PIN }}
          TOTP_KEY: ${{ secrets.TOTP_KEY }}
        run: python Nifty500_PDF_DoublePattern.py # <-- IMPORTANT: Replace with your actual script file name

      # 5. Sends the generated PDF via email
      - name: Send email with PDF attachment
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com # Use your email provider's SMTP server
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: Double Bottom Stock Report - ${{ github.workflow }} - $(date +'%d-%b-%Y')
          body: |
            Please find the attached stock analysis report for today.
            
            Generated by GitHub Actions.
          to: ${{ secrets.EMAIL_USER }}
          from: GitHub Actions Bot <${{ secrets.EMAIL_USER }}>
          attachments: NIFTY500_Different_Patterns.pdf
